### ISSUE TITLE
cannot launch nvb after successful install

### ISSUE THREAD

**Issue by capnahab** [alpha2phi/neovim-for-beginner#21]
Great tutorials. I have installed nvb on Mac Monterey (12.1) MBP . After the initial succcessful launch and restart terminal nvb fails to launch with the following

```
Error detected while processing function <SNR>13_LoadRemotePlugins[1]..<SNR>13_GetManifest[1]..<SNR>13_GetManifestPath:
line   10:
E739: Cannot create directory /share: read-only file system
```
in the terminal and tries to open default NVIM. 

I have an aliases file .zsh_aliases and have put the alias in there. 

Looking at :scriptnames , script 13 is rplugin which I didnt know I had.

**Comment by mengwangk** [comment]
Most likely the the alias and the XDG variables are not configured correctly. Can you check on that?
