### ISSUE TITLE
BufWritePre AutoCommands error

### ISSUE THREAD

**Issue by Mounir-Bennacer** [alpha2phi/neovim-for-beginner#55]
Hi,

thank you for your work, it's an amazing config when everything is working, but in my case i'm having trouble getting nul-ls working as i get an error each time i save the file

i work mainly with javascript but from time to time i use python and go

here is a screenshot about the error if that could help debugging it:
<img width="1122" alt="Screenshot 2022-05-16 at 14 30 16" src="https://user-images.githubusercontent.com/48013502/168604603-57b99afc-5268-40fe-ba3d-7630486cf455.png">

**Comment by mengwangk** [comment]
Hi,

This should be fixed in the main branch. Can you try again?
